name: PR ì•Œë¦¼ to Discord

on:
  pull_request:
    types: [ opened ]

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discordì— PR ì•Œë¦¼ ì „ì†¡
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL_BE_PR_NOTIFY }}
          message: |
            ğŸš€ ìƒˆë¡œìš´ PRì´ ìƒì„±ë˜ì—ˆìŠµë‹ˆë‹¤!  
            PR ì œëª©: **${{ github.event.pull_request.title }}**  
            ì‘ì„±ì: **${{ github.event.pull_request.user.login }}**  
            ğŸ”— [PR ë§í¬](${{ github.event.pull_request.html_url }})
